### ISSUE TITLE
Make random_value() to generate cryptographically strong random values

### ISSUE THREAD

**Issue by pnowosie** [robconery/pg-auth#7]
When generating random strings for authentication it is good idea to make it unpredictable. Since we have dependency of pg_crypto we can use gen_random_bytes() function

``` PLpgSQL
SELECT substring( encode(gen_random_bytes(len /2 +1), 'hex'), 0, len ) into result;
```

If we accept non-alphanumeric characters in random strings, we could use 'base64' encoding which compared to hex has more entropy in the same length string:

``` PLpgSQL
SELECT substring( encode(gen_random_bytes(len * 3/4 +1), 'base64'), 0, len ) into result;
```

This is even more important in [your's node-db-project](https://github.com/robconery/node-db-project) when you generate user's auth token. Does this make sense?

**Comment by robconery** [comment]
Yep - I like it. To be sure I understand - the current use of MD5 and random() doesn't provide this level of unpredictability? If I understand the math, random() returns a rather long number which has a 1 in a quadrillion of being repeated. I'm all for something stronger...

**Comment by pnowosie** [comment]
Yes, you got it right. Event if random number looks enough "random and unpredictable" knowing the exact time of when it was generated could drive some smart guy to reconstruct it somehow :) BTW [Postgres' docs](http://www.postgresql.org/docs/9.4/static/functions-math.html#FUNCTIONS-MATH-RANDOM-TABLE) mentions that random() is not suitable for crypto.

**Comment by robconery** [comment]
Interesting point - believe me I'm not trying to brush you off I'm wanting to see the issue more clearly. There are two points being raised: the first is _randomness_ and the second is _reverse engineering_. The latter is important because the `auth_token` will allow someone into the system.

If I understand you, you're suggesting that if a Bad Guy uses a timestamp, he/she can recreate the random number that was generated by `random()`. If I understand the way PG implements `random()` (based on some Googling) - [it's using this algorithm here](https://en.wikipedia.org/wiki/Linear_congruential_generator), which doesn't seem to have much to do with time.

Your final point about using it for cryptography is well-taken, and I'm not doing that. I'm generating a unique, random string which isn't being used in any form of cryptographic functionality. 

So... if I understand your points: I'd like to see more about guessing the value of `random()` using a timestamp. I certainly don't want anything to be guessable - so I'm not necessarily challenging you on this (more secure is almost always better) - I'm just wondering if we're way off on a fringe topic here or if there's something I'm not seeing.

Also - if you'd like to PR something on this, please do :).

**Comment by pnowosie** [comment]
I'm not going to defend my previous comment. I think I failed to express myself, used too many shortcuts, and suggesting that you did something wrong was not my intention (foreign english). 

I just wanted to say, that using crypto-strong PRNG seems to be more recommended approach, let's make it a little bit harder for bad guys. I can see it has nothing to do with cryptography, I totally messed up with explanation ;)

I will PR soon.

**Comment by robconery** [comment]
Not at all - this is a great conversation :) I just want to make sure it applies and solves a problem is all :).

**Comment by robconery** [comment]
I don't know how I missed this... sorry!
